trigger: none

pr:
  branches:
    include:
      - main
  paths:
    include:
      - eng/scripts/bompreperation.yml

stages:
  - stage: AnalyzeAndGeneratePatches

    jobs:
      - job: PatchGeneration
        timeoutInMinutes: 180

        pool:
          vmImage: 'windows-2019'

        steps:
        - pwsh: /eng/scripts/patchreleases.ps1