trigger: none

pr:
  branches:
    include:
      - main
  paths:
    include:
      - eng/scripts/bompreperation.yml

stages:
  - stage: AnalyzeAndGeneratePatches

    jobs:
      - job: PatchGeneration
        timeoutInMinutes: 180

        pool:
          vmImage: 'windows-2019'

        steps:
        - pwsh: |
            $(Build.SourcesDirectory)/eng/scripts/patchreleases.ps1
            Copy-Item eng/scripts/ReleasePatchInfo.csv $(Build.ArtifactStagingDirectory)/staging
        displayName: 'Analyze and generate patches'